services:
  db:
    image: postgres:16-alpine
    container_name: whiteboard_notes_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: whiteboard_notes
    ports:
      - "5433:5432"
    volumes:
      - whiteboard_notes_pgdata:/var/lib/postgresql/data

volumes:
  whiteboard_notes_pgdata:
